export const mostMenDontMissTheSportBody: string[] = [
  "An 18-year-old former athlete from Northern Europe described the first months after leaving organized sport as \"quiet in a way that felt physically wrong.\" Not peaceful. Not relaxing. Wrong.",
  "For years, his life had been divided into clean lines. Wake up. Train. Eat. Recover. Perform. Repeat. The structure was demanding, but it was also comforting. Every hour already knew what it was supposed to become before it even arrived.",
  "Then it ended.",
  "Not dramatically. No career-ending injury. No public collapse. Just the slow realization that the version of himself built around performance no longer had a place to go.",
  "A lot of young men experience this long before they know how to describe it.",
  "The problem is rarely just the loss of competition itself. Most people assume former athletes miss the adrenaline, the crowd, or the game-day atmosphere. Some do. But that explanation is incomplete. What many of them actually miss is the psychological architecture that performance gave their lives.",
  "Sport gave them an identity before they had to build one themselves.",
  "In structured environments, identity is outsourced. The rules already exist. The hierarchy exists. Expectations exist. You know where to be, what matters, and how progress is measured. Even suffering feels meaningful because it happens inside a system that validates it.",
  "Outside of that structure, things become less clear.",
  "A surprising number of high-performing young men realize that much of their confidence was situational. It depended on competence. On routine. On knowing exactly who they were in relation to other people.",
  "Take away the environment and the personality becomes harder to locate.",
  "This is one of the stranger psychological consequences of intense performance culture. A person can become extremely disciplined without ever developing a stable sense of self outside the system rewarding that discipline.",
  "A former athlete knows how to wake up at six in the morning. He knows how to push through exhaustion. He knows how to ignore discomfort. But many of them quietly admit they have no idea who they are when nobody is measuring them anymore.",
  "Modern culture tends to romanticize discipline as an unquestionable virtue. Discipline is presented as the answer to almost everything — anxiety, confusion, uncertainty, stagnation. And to some extent, discipline matters. Structure matters. But discipline can also become a form of emotional avoidance.",
  "If every moment of your life is organized around performance, there is very little room left to ask more uncomfortable questions.",
  "Who are you without the routine?",
  "Who are you when your usefulness disappears for a while?",
  "Who are you when there is no external scoreboard confirming that you still matter?",
  "A lot of ambitious young men are terrified of those questions. Not because they are weak, but because they have spent years building themselves around systems that rewarded output above introspection.",
  "The transition out of those systems can feel psychologically disorienting in ways that are difficult to explain to people who have never lived inside them.",
  "One former junior hockey player described the months after retirement as \"socially confusing.\" During his playing years, most friendships formed automatically through shared structure — locker rooms, buses, practices, tournaments, training schedules. Once the structure disappeared, maintaining connection suddenly required emotional initiative rather than proximity.",
  "That sounds minor until you experience it firsthand.",
  "A structured environment quietly carries large parts of your emotional life for you. It decides where you spend your time. It decides who you see regularly. It creates rituals, goals, routines, language, and belonging. Once it disappears, many people discover they were relying on the structure more heavily than they realized.",
  "This is why some former athletes continue training obsessively long after competition stops mattering to them. They are not always chasing physical improvement. Sometimes they are trying to recreate psychological familiarity.",
  "The gym becomes less about fitness and more about continuity.",
  "There is also a masculine dimension to all of this that rarely gets discussed honestly.",
  "A lot of young men learn very early that love, respect, and attention become more available when they are useful, productive, competent, or impressive. Performance becomes emotionally tied to self-worth. The athlete who succeeds receives validation not only for what he does, but gradually for who he is.",
  "The danger appears when performance stops.",
  "If your identity is built almost entirely around competence, failure becomes existential. Rest feels threatening. Confusion feels shameful. Slowness feels morally wrong.",
  "Many ambitious men secretly experience periods of transition as personal failure because they no longer know how to measure themselves outside systems built around achievement.",
  "That is partly why modern \"grind culture\" becomes so appealing. It offers certainty. Simplicity. A replacement structure. Keep working. Keep optimizing. Keep improving. Never stop moving long enough to notice the emptiness underneath.",
  "But eventually most people encounter a moment where performance alone stops solving the deeper problem.",
  "The structure ends.",
  "The relationship ends.",
  "The season ends.",
  "The university program ends.",
  "The military contract ends.",
  "And suddenly there is no externally imposed identity left to inhabit.",
  "What happens next is rarely cinematic. Most transitions are quiet. They happen in apartments, gyms, trains, empty kitchens, late-night walks, and conversations that never fully explain what is actually being felt.",
  "A young man wakes up one morning and realizes nobody is waiting for him to become a specific version of himself anymore.",
  "At first, that freedom can feel like panic.",
  "Then eventually, if he is fortunate, it begins to feel like responsibility.",
  "There is a difference between structure given to you and structure chosen consciously. The second is slower. Less dramatic. Less externally validated. But it is usually more honest.",
  "The difficult part is enduring the period in between.",
  "The period where the old identity no longer fits but the new one has not fully formed yet.",
  "Most people try to escape that phase as quickly as possible. They rush toward new labels, new ambitions, new identities, new systems. Anything to avoid uncertainty. But some transitions cannot be solved through speed. They have to be lived through slowly.",
  "That process is rarely visible online because modern internet culture rewards certainty far more than ambiguity. Everyone wants to appear transformed already. Few people are willing to admit they are still rebuilding.",
  "But rebuilding is probably closer to the real human experience.",
  "Not reinvention. Reconstruction.",
  "Piece by piece.",
  "The strange thing is that many former athletes eventually realize they never actually wanted to keep playing forever. What they wanted was the feeling the structure gave them: direction, coherence, momentum, belonging.",
  "Once they understand that distinction, something changes.",
  "The grief becomes less confusing.",
  "Because the sport was never the entire story.",
  "It was simply the environment where a certain version of themselves once made sense.",
];
